/**
 * Important: Do not edit this file.
 */
export { QueueProcessor } from './queue/QueueProcessor';
export { Document } from './queue/Document';
import journal from './data/journal.json'; //This import is required in order to use the FileDriver
